seven_dof_arm:
  # 모든 조인트 상태를 발행 -----------------------------------
  joint_state_publisher:
    type : joint_state_controller/JointStateController
    publish_rate : 50
  # 위치 컨트롤러 -------------------------------------------
  joint1_position_controller:
    type : position_controllers/JointPositionController
    joint : shoulder_pan_joint
    pid : {p: 100.0, i: 0.01, d: 10.0}
  joint2_position_controller:
    type : position_controllers/JointPositionController
    joint : shoulder_pitch_joint
    pid : {p: 100.0, i: 0.01, d: 10.0}
  joint3_position_controller:
    type : position_controllers/JointPositionController
    joint : elbow_roll_joint
    pid : {p: 100.0, i: 0.01, d: 10.0}
  joint4_position_controller:
    type : position_controllers/JointPositionController
    joint : elbow_pitch_joint
    pid : {p: 100.0, i: 0.01, d: 10.0}
  joint5_position_controller:
    type : position_controllers/JointPositionController
    joint : wrist_roll_joint
    pid : {p: 100.0, i: 0.01, d: 10.0}
  joint6_position_controller:
    type : position_controllers/JointPositionController
    joint : wrist_pitch_joint
    pid : {p: 100.0, i: 0.01, d: 10.0}
  joint7_position_controller:
    type : position_controllers/JointPositionController
    joint : gripper_roll_joint
    pid : {p: 100.0, i: 0.01, d: 10.0}